### ISSUE TITLE
build fails on line 22

### ISSUE THREAD

**Issue by nomadbl** [karlprieb/writefreely-docker#1]
Hello!
Trying to build the image and running into an error on line 22 of the Dockerfile. i.e. either on "make build" or on "make ui".
The relevant parts from docker-compose.yml:

```
services:
  writefreely:
    build:
      context: ./writefreely-docker
      args:
        - REPOSITORY=$REPOSITORY
        - VERSION=$VERSION
    restart: unless-stopped
    volumes:
      - ./writefreely-docker/config:/config:Z
      - ./writefreely-docker/data:/data:Z
```
      
In .env I only put a user name and passowrd. Haven't touched the config file for now.
The file tree is:
```
/
docker-compose.yml
.env
    /writefreely-docker
    <all the docker files (where env is usually)>
```
